#Examples of config settings

#Example 1
#module: "ml_project.models.transformer"
#class: "RandomSelection"
#action: "fit_transform"
#params:
#  n_components: 1000
#  random_state: 37

#Example 2
#module: "sklearn.linear_model"
#class: "LinearRegression"
#action: "fit"
#params:
#  normalize: True

module: ml_project.models.crossvalidation
class: GridSearchCV
action: fit
params:
  est_module: ml_project.models.crossvalidation
  est_class: Pipeline
  est_params:
    - module: ml_project.models.transformer
      class: RandomSelection
      params:
        random_state: 37
    - module: sklearn.linear_model
      class: LinearRegression
  param_grid:
    RandomSelection__n_components:
      - 100
      - 1000
      - 10000